# Generated by Django 3.0.3 on 2020-03-04 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_title', models.CharField(max_length=200, verbose_name='Назва ресторану')),
                ('restaurant_text', models.TextField(verbose_name='текст ресторану')),
                ('pub_date', models.DateTimeField(verbose_name='дата чогось-там')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=50, verbose_name='автор')),
                ('comment_text', models.CharField(max_length=200, verbose_name='текст комент')),
                ('restaurant',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.Restaurant')),
            ],
        ),
    ]
