# Generated by Django 3.0.3 on 2020-03-05 11:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='restaurant_text',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='restaurant_title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='rating',
            field=models.FloatField(default=0, verbose_name='рейтинг'),
            preserve_default=False,
        ),
    ]
