# Generated by Django 3.0.3 on 2020-03-19 10:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('restaurants', '0002_auto_20200305_1424'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dishes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_name', models.CharField(max_length=100, verbose_name='name')),
                ('dish_description', models.TextField(verbose_name='опис страви')),
                ('dish_price', models.FloatField(verbose_name='ціна')),
            ],
        ),
    ]
