# Generated by Django 3.0.3 on 2020-03-19 10:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('restaurants', '0003_dishes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dishes',
            new_name='Course',
        ),
    ]
