# Generated by Django 3.0.3 on 2020-04-06 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('restaurants', '0004_auto_20200319_1330'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_name', models.CharField(max_length=100, verbose_name='name')),
                ('dish_description', models.TextField(verbose_name='опис страви')),
                ('dish_price', models.FloatField(verbose_name='ціна')),
                ('restaurant',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.Restaurant')),
            ],
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
