# Generated by Django 3.0.3 on 2020-04-06 13:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('restaurants', '0005_auto_20200406_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='dish_name',
            field=models.CharField(max_length=100, verbose_name='назва страви'),
        ),
    ]
