# Generated by Django 3.0.3 on 2020-04-12 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_auto_20200406_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='dish_time_cook',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='dish_weight',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_text',
            field=models.CharField(max_length=300, verbose_name='текст комент'),
        ),
    ]
