# Generated by Django 3.0.3 on 2020-04-12 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0007_auto_20200412_1102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='rating',
        ),
        migrations.AddField(
            model_name='comment',
            name='rating',
            field=models.FloatField(null=True),
        ),
    ]
