# Generated by Django 3.0.5 on 2020-05-02 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0008_auto_20200412_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='dish_time_cook',
            field=models.FloatField(null=True, verbose_name='час приготування'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='dish_weight',
            field=models.FloatField(null=True, verbose_name='вага'),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drinks', models.TextField(verbose_name='напої')),
                ('alcoholic_drinks', models.TextField(verbose_name='алкогольні напої')),
                ('pizza', models.TextField(verbose_name='піцци')),
                ('salads', models.TextField(verbose_name='салати')),
                ('dessert', models.TextField(verbose_name='десерти та млинці')),
                ('sushi', models.TextField(verbose_name='суші та роли')),
                ('main_course', models.TextField(verbose_name='основні страви')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.Menu')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.Restaurant')),
            ],
        ),
    ]
